function Vcyl_mm3 = cylinder_volume_mm3_matlab(theta,V_c,a,l,B)
%CYLINDER_VOLUME_MM3_MATLAB
%    VCYL_MM3 = CYLINDER_VOLUME_MM3_MATLAB(THETA,V_C,A,L,B)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    12-Apr-2018 17:24:05

Vcyl_mm3 = V_c+B.^2.*pi.*(a+l-a.*cos(theta)-sqrt(-a.^2.*sin(theta).^2+l.^2)).*(1.0./4.0);
