function out1 = throttleParamEqs(in1,S_leak,D_thr,theta_rest)
%THROTTLEPARAMEQS
%    OUT1 = THROTTLEPARAMEQS(IN1,S_LEAK,D_THR,THETA_REST)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    16-Apr-2018 14:12:03

k_0 = in1(:,1);
k_1 = in1(:,2);
k_2 = in1(:,3);
k_3 = in1(:,4);
t2 = pi.^2;
t3 = D_thr.^2;
t4 = pi.*(1.0./6.0e1);
t5 = cos(theta_rest);
t6 = 1.0./t5;
out1 = [-S_leak+k_0+k_1.*pi.*(1.0./6.0e1)+k_2.*t2.*2.777777777777778e-4+t3.*pi.*(t6.*cos(t4)-1.0).*(1.0./4.0)+k_3.*t2.*pi.*4.62962962962963e-6;-S_leak+k_0+k_1.*pi.*(1.0./2.0)-t3.*pi.*(1.0./4.0)+k_2.*t2.*(1.0./4.0)+k_3.*t2.*pi.*(1.0./8.0);k_1+k_2.*pi.*(1.0./3.0e1)+k_3.*t2.*8.333333333333333e-4-t3.*t6.*pi.*sin(t4).*(1.0./4.0);k_1+k_2.*pi+k_3.*t2.*(3.0./4.0)];
