function out1 = volumetricEfficiencyParams(F_0,x_peak,F_peak,x_max,F_xmax)
%VOLUMETRICEFFICIENCYPARAMS
%    OUT1 = VOLUMETRICEFFICIENCYPARAMS(F_0,X_PEAK,F_PEAK,X_MAX,F_XMAX)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    15-Apr-2018 11:33:27

t2 = x_max.^2;
t3 = x_peak.^2;
t4 = t3.*x_max;
t8 = t2.*x_peak.*2.0;
t5 = t4-t8+t2.*x_max;
t6 = 1.0./t5;
t7 = 1.0./x_peak.^2;
out1 = [F_0,-(t6.*(F_0.*t2.*x_max.*2.0-F_0.*t2.*x_peak.*3.0+F_0.*t3.*x_peak-F_peak.*t2.*x_max.*2.0+F_peak.*t2.*x_peak.*3.0-F_xmax.*t3.*x_peak))./x_peak,t6.*t7.*(F_0.*t2.*x_max-F_0.*t3.*x_max.*3.0+F_0.*t3.*x_peak.*2.0-F_peak.*t2.*x_max+F_peak.*t3.*x_max.*3.0-F_xmax.*t3.*x_peak.*2.0),-t6.*t7.*(F_0.*t2+F_0.*t3-F_peak.*t2-F_xmax.*t3-F_0.*x_max.*x_peak.*2.0+F_peak.*x_max.*x_peak.*2.0)];
