% Copyright 2018 The MathWorks, Inc.    
p = slproject.getCurrentProjects;

myCacheFolder = fullfile(p.RootFolder,'work');
myCodeGenFolder = fullfile(p.RootFolder,'work');

Simulink.fileGenControl('set', ...
   'CacheFolder',myCacheFolder, ...
   'CodeGenFolder',myCodeGenFolder, ...
   'keepPreviousPath',true, ...
   'createDir',true);

